export const npcDefaults = {
  agnes: {
    classe: "Guarda",
    nome: "Guarda",
    nomeVerdadeiro: "Agnes",
    arquetipo: "Fanática",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "agnes",
    video: "agnes",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  alice: {
    classe: "Operária",
    nome: "Operária",
    nomeVerdadeiro: "Alice",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 1,
    relacao: "Neutro",
    imagem: "alice",
    video: "alice",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  andrew: {
    classe: "Guarda",
    nome: "Guarda",
    nomeVerdadeiro: "Andrew",
    arquetipo: "Quebrado",
    status: "Saudável",
    nivelAcesso: 2,
    relacao: "Neutro",
    imagem: "andrew",
    video: "andrew",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  guest: {
    classe: "IA",
    nome: "IA",
    nomeVerdadeiro: "A Convidada",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "guest",
    video: "guest",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  hana: {
    classe: "Cientista",
    nome: "Cientista",
    nomeVerdadeiro: "Hana",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 1,
    relacao: "Neutro",
    imagem: "hana",
    video: "hana",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  jordan: {
    classe: "Guarda",
    nome: "Guarda",
    nomeVerdadeiro: "Jordan",
    arquetipo: "Conflituoso",
    status: "Saudável",
    nivelAcesso: 1,
    relacao: "Neutro",
    imagem: "jordan",
    video: "jordan",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  kasper: {
    classe: "Guarda",
    nome: "Guarda",
    nomeVerdadeiro: "Kasper",
    arquetipo: "Fanático",
    status: "Saudável",
    nivelAcesso: 2,
    relacao: "Neutro",
    imagem: "kasper",
    video: "kasper",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  kenneth: {
    classe: "Guarda",
    nome: "Guarda",
    nomeVerdadeiro: "Kenneth",
    arquetipo: "Funcional",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "kenneth",
    video: "kenneth",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  kiara: {
    classe: "Operária",
    nome: "Operária",
    nomeVerdadeiro: "Kiara",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 1,
    relacao: "Neutro",
    imagem: "kiara",
    video: "kiara",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  liam: {
    classe: "Cientista",
    nome: "Cientista",
    nomeVerdadeiro: "Liam",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 1,
    relacao: "Neutro",
    imagem: "liam",
    video: "liam",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  lochlan: {
    classe: "Operário",
    nome: "Operário",
    nomeVerdadeiro: "Lochlan",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "lochlan",
    video: "lochlan",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  lorelai: {
    classe: "Cientista",
    nome: "Cientista",
    nomeVerdadeiro: "Lorelai",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 2,
    relacao: "Neutro",
    imagem: "lorelai",
    video: "lorelai",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  lucilla: {
    classe: "Cientista",
    nome: "Cientista-Chefe",
    nomeVerdadeiro: "Lucilla Valtesia",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "lucilla",
    video: "lucilla",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  mikayla: {
    classe: "Guarda",
    nome: "Guarda",
    nomeVerdadeiro: "Mikayla",
    arquetipo: "Funcional",
    status: "Saudável",
    nivelAcesso: 1,
    relacao: "Neutro",
    imagem: "mikayla",
    video: "mikayla",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  octavia: {
    classe: "Cientista",
    nome: "Cientista",
    nomeVerdadeiro: "Octavia",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "octavia",
    video: "octavia",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  oliver: {
    classe: "Operário",
    nome: "Operário",
    nomeVerdadeiro: "Oliver",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 3,
    relacao: "Neutro",
    imagem: "oliver",
    video: "oliver",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },

  roy: {
    classe: "Operário",
    nome: "Operário",
    nomeVerdadeiro: "Roy",
    arquetipo: "",
    status: "Saudável",
    nivelAcesso: 2,
    relacao: "Neutro",
    imagem: "roy",
    video: "roy",
    descoberto: false,
    videoDescobertaExibido: false,
    revelado: {
      nome: false,
      arquetipo: false,
      status: false,
      nivelAcesso: false,
      relacao: false,
    },
  },
};